<a href="https://colab.research.google.com/github/VijayTaori/Lifo_step1/blob/main/CFDs2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import pandas as pd
import numpy as np
import datetime as dt
import time
import calendar

In [51]:
df_eur2usd = pd.read_csv('/content/eur_usd_all_plus_weekends.csv')
df_eur2usd['Date'] = pd.to_datetime(df_eur2usd['Date'],dayfirst=True)

In [44]:
df = pd.read_excel('Assesment of taxes 2020_etoro.xlsx', sheet_name=2)

In [11]:
df.columns

Index(['Position ID', 'Action', 'Amount', 'Units', 'Units (cal)', 'Open Date',
       'Close Date', 'Leverage', 'Spread', 'Profit', 'Unnamed: 10',
       'Open Rate', 'Close Rate', 'profit (cl-op)*units', 'Unnamed: 14',
       'Close Amount', 'Rollover Fees and Dividends', 'Type', 'x', 'y',
       'Unnamed: 20', 'profit', 'ActionType'],
      dtype='object')

In [46]:
def sell_buy(action_item):
  sell_buy_item = action_item.split()[0]
  return sell_buy_item
df['ActionType'] = df['Action'].map(sell_buy)

In [47]:
df['ActionType'].unique()

array(['Sell', 'Buy'], dtype=object)

In [48]:
df_sell = df[df['ActionType'] == 'Sell']
df_buy = df[df['ActionType'] == 'Buy']

In [53]:
df_sell_open = df_sell[['Position ID','ActionType','Action', 'Amount', 'Units', 'Leverage','Open Date', 'Open Rate']]
df_sell_close = df_sell[['Position ID', 'ActionType','Action', 'Units','Leverage', 'Close Date', 'Spread',
                    'Close Rate', 'Profit','Rollover Fees and Dividends']]

In [54]:
df_buy_open = df_buy[['Position ID','ActionType','Action', 'Amount', 'Units', 'Leverage','Open Date', 'Open Rate']]
df_buy_close = df_buy[['Position ID', 'ActionType','Action', 'Units','Leverage', 'Close Date', 'Spread',
                    'Close Rate', 'Profit','Rollover Fees and Dividends']]

In [52]:
df_buy_close

,Position ID,ActionType,Action,Units,Leverage,Close Date,Spread,Close Rate,Profit,Rollover Fees and Dividends
3,845829079,Buy,Buy Meta Platforms Inc,1.875610,5,29/12/2020 18:06:06,0.94,277.56,20.59,-0.63
4,845839951,Buy,Buy Meta Platforms Inc,1.870487,5,29/12/2020 18:06:00,0.94,277.57,19.19,-0.63
5,843269002,Buy,Buy Meta Platforms Inc,1.852332,5,29/12/2020 18:05:53,0.93,277.57,14.15,-0.72
6,845060804,Buy,Buy Meta Platforms Inc,1.850687,5,29/12/2020 18:05:47,0.93,277.61,13.77,-0.63
7,835490794,Buy,Buy Meta Platforms Inc,1.810479,5,29/12/2020 18:05:38,0.91,277.58,2.55,-1.16
...,...,...,...,...,...,...,...,...,...,...
445,755538722,Buy,"Buy Tesla Motors, Inc.",0.568402,5,09/10/2020 14:09:58,0.44,429.76,1.35,-0.13
446,755378788,Buy,"Buy Tesla Motors, Inc.",0.584893,5,09/10/2020 13:34:46,0.45,427.75,0.22,-0.13
447,753749828,Buy,Buy SPX500 Index,1.173014,20,08/10/2020 09:14:44,0.82,3431.77,5.51,0.00
449,753535508,Buy,"Buy Tesla Motors, Inc.",0.582711,5,07/10/2020 18:32:13,0.45,427.71,0.19,-0.04
450,753535233,Buy,"Buy Tesla Motors, Inc.",0.584344,5,07/10/2020 18:31:44,0.45,427.54,0.09,-0.04

In [ ]:
df_sell_open['Open Date'] = pd.to_datetime(df_sell_open['Open Date'],dayfirst=True)
df_sell_close['Close Date'] = pd.to_datetime(df_sell_close['Close Date'],dayfirst=True)
df_buy_open['Open Date'] = pd.to_datetime(df_buy_open['Open Date'],dayfirst=True)
df_buy_close['Close Date'] = pd.to_datetime(df_buy_close['Close Date'],dayfirst=True)

In [ ]:
df_sell_open.dtypes

In [56]:
def datetime2date(date_time):
  date = date_time.date()
  return date

In [ ]:
df_sell_open['Date'] = df_sell_open['Open Date'].map(datetime2date)
df_sell_close['Date'] = df_sell_close['Close Date'].map(datetime2date)
df_buy_open['Date'] = df_buy_open['Open Date'].map(datetime2date)
df_buy_close['Date'] = df_buy_close['Close Date'].map(datetime2date)

In [ ]:
df_sell_open['Date'] = pd.to_datetime(df_sell_open['Date'],dayfirst=True)
df_sell_close['Date'] = pd.to_datetime(df_sell_close['Date'],dayfirst=True)
df_buy_open['Date'] = pd.to_datetime(df_buy_open['Date'],dayfirst=True)
df_buy_close['Date'] = pd.to_datetime(df_buy_close['Date'],dayfirst=True)

In [ ]:
df_sell_close.dtypes

In [ ]:
df_find_na = df_buy_close # use the DataFrame for which you would like to find NANs
columns_df_find_na = df_find_na.columns
def find_null_values(column_name):
  print('The number of null values in column {} are:'.format(column_name),len(np.where(df_find_na.isna()[column_name])[0]))
  print('And their integer location is:', np.where(df_find_na.isna()[column_name])[0])
null_values = [find_null_values(y) for y in columns_df_find_na]

In [36]:
print(df_sell_open.shape)
print(df_sell_close.shape)

(76, 9)
(76, 11)

In [37]:
print(df_buy_open.shape)
print(df_buy_close.shape)

(375, 9)
(375, 11)

In [59]:
df_sell_open_eur = pd.merge(df_sell_open, df_eur2usd, on='Date')
df_sell_close_eur = pd.merge(df_sell_close, df_eur2usd, on='Date')
df_buy_open_eur = pd.merge(df_buy_open, df_eur2usd, on='Date')
df_buy_close_eur = pd.merge(df_buy_close, df_eur2usd, on='Date')

In [ ]:
df_find_na = df_buy_close_eur # use the DataFrame for which you would like to find NANs
columns_df_find_na = df_find_na.columns
def find_null_values(column_name):
  print('The number of null values in column {} are:'.format(column_name),len(np.where(df_find_na.isna()[column_name])[0]))
  print('And their integer location is:', np.where(df_find_na.isna()[column_name])[0])
null_values = [find_null_values(y) for y in columns_df_find_na]

In [64]:
print(df_sell_open.shape)
print(df_sell_close.shape)

(76, 9)
(76, 11)

In [65]:
print(df_buy_open.shape)
print(df_buy_close.shape)

(375, 9)
(375, 11)

In [ ]:
df_sell_open_eur

In [ ]:
df_sell_close_eur

In [82]:
df_eur_sell = pd.merge(df_sell_open_eur, df_sell_close_eur, on=['Position ID', 'Action','ActionType', 'Units','Leverage'])
df_eur_buy = pd.merge(df_buy_open_eur, df_buy_close_eur, on=['Position ID', 'Action','ActionType', 'Units','Leverage'])

In [72]:
print(df_eur_sell.shape)
print(df_eur_buy.shape)

(76, 25)
(375, 25)

In [87]:
df_eur_buy.columns

Index(['Position ID', 'ActionType', 'Action', 'Amount', 'Units', 'Leverage',
       'Open Date', 'Open Rate', 'Date_x', 'Open_x', 'High_x', 'Low_x',
       'Close_x', 'Weekday_x', 'Close Date', 'Spread', 'Close Rate', 'Profit',
       'Rollover Fees and Dividends', 'Date_y', 'Open_y', 'High_y', 'Low_y',
       'Close_y', 'Weekday_y', 'Amount_open_Eur', 'Open Rate_Eur',
       'Close Rate_Eur', 'Spread_Eur', 'Fee_Eur', 'diff_rates', 'profit_1_eur',
       'real_profit_eur', 'Close_amount_eur'],
      dtype='object')

In [88]:
df_eur_buy_trimmed = df_eur_buy[['Position ID', 'Action', 'Amount','Amount_open_Eur', 'Close_amount_eur','Units', 'Leverage',
                                 'Open Date','Date_x','Close Date','Date_y',  'Open Rate', 'Open Rate_Eur', 'Spread', 'Spread_Eur',
                                 'Close Rate', 'Close Rate_Eur','Profit', 'profit_1_eur', 'real_profit_eur' ,
                                 'Rollover Fees and Dividends', 'Fee_Eur', 'diff_rates']]

In [100]:
df_trimmed = df_eur_buy_trimmed[['Action', 'Amount','Amount_open_Eur', 'Close_amount_eur','Units', 'Leverage','Open Rate_Eur','Close Rate_Eur','Profit','profit_1_eur']]

In [101]:
df_trimmed['profit_1_eur'].min()

-853.3940567535263

In [102]:
df_trimmed[df_trimmed['profit_1_eur'] == -853.3940567535263]

,Action,Amount,Amount_open_Eur,Close_amount_eur,Units,Leverage,Open Rate_Eur,Close Rate_Eur,Profit,profit_1_eur
267,"Buy Tesla Motors, Inc.",2000.0,1708.680267,824.933391,23.053161,5,370.595663,333.577136,-1000.05,-853.394057

In [110]:
df_eur_buy['Amount_open_Eur'] = df_eur_buy['Amount']/df_eur_buy['Low_x']
df_eur_buy['Open Rate_Eur'] = df_eur_buy['Open Rate']/df_eur_buy['Low_x']
df_eur_buy['Close Rate_Eur'] = df_eur_buy['Close Rate']/df_eur_buy['High_y']
df_eur_buy['Spread_Eur'] = df_eur_buy['Spread']/df_eur_buy['Low_y']
df_eur_buy['Fee_Eur'] = df_eur_buy['Rollover Fees and Dividends']/df_eur_buy['Low_y']
df_eur_buy['diff_rates'] = df_eur_buy['Close Rate_Eur'] - df_eur_buy['Open Rate_Eur']
df_eur_buy['profit_1_eur'] = df_eur_buy['diff_rates'] * df_eur_buy['Units']
df_eur_buy['real_profit_eur'] = df_eur_buy['profit_1_eur'] + df_eur_buy['Fee_Eur'] - df_eur_buy['Spread_Eur']
df_eur_buy['Close_amount_eur'] = df_eur_buy['real_profit_eur'] + df_eur_buy['Amount_open_Eur']
df_eur_buy['Profit_Diff'] = df_eur_buy['real_profit_eur'] - df_eur_buy['Profit']

In [111]:
df_eur_buy_profit_sort = df_eur_buy.sort_values(by='Profit_Diff')

In [113]:
df1 = df_eur_buy_profit_sort[['Action', 'Amount','Amount_open_Eur', 'Close_amount_eur','Profit','profit_1_eur','Profit_Diff', 'Units', 'Leverage','Open Rate_Eur','Close Rate_Eur']]

In [114]:
df1[0:20]

,Action,Amount,Amount_open_Eur,Close_amount_eur,Profit,profit_1_eur,Profit_Diff,Units,Leverage,Open Rate_Eur,Close Rate_Eur
172,Buy NASDAQ100 Index,1000.0,861.500078,624.429107,2.92,-233.521591,-239.990971,1.717269,20,10033.374513,9897.390232
166,Buy SPX500 Index,800.0,689.200063,529.187093,37.45,-157.178634,-197.462970,4.699331,20,2936.311022,2902.863999
165,Buy SPX500 Index,800.0,689.200063,505.745135,9.63,-180.620593,-193.084928,4.696710,20,2934.820627,2896.363794
333,Buy NASDAQ100 Index,700.0,593.824228,948.271817,468.77,356.865302,-114.322411,1.186320,20,10011.197828,10312.014894
290,Buy NASDAQ100 Index,1000.0,855.420285,781.125846,37.13,-70.829987,-111.424439,1.687550,20,10138.013509,10096.041427
239,Buy NASDAQ100 Index,1400.0,1197.097893,392.046501,-696.93,-794.406313,-108.121391,2.333226,20,10261.138355,9920.662844
289,Buy DJ30 Index,1000.0,855.420285,749.094515,-0.35,-102.698788,-105.975770,0.706720,20,24208.180213,24062.862706
82,Buy Amazon.com Inc,1000.0,827.759751,857.041592,129.60,44.192708,-100.318159,1.586904,5,2608.097146,2635.945527
340,Buy NASDAQ100 Index,1000.0,850.429807,762.490710,12.00,-84.443830,-99.939097,1.713965,20,9923.537856,9874.269738
339,Buy SPX500 Index,1000.0,850.429807,758.258222,6.92,-88.735849,-99.091585,5.768876,20,2948.338090,2932.956264
9,Buy Amazon.com Inc,1000.0,824.349979,912.078712,184.13,101.231176,-96.401268,1.556444,5,2648.183091,2713.223129
64,Buy Silver,700.0,574.125791,828.748600,350.27,266.485205,-95.647191,269.438029,10,21.308269,22.297309
243,Buy NASDAQ100 Index,1000.0,855.069923,827.625416,60.36,-24.015677,-87.804508,1.671954,20,10228.389177,10214.025338
83,Buy Amazon.com Inc,900.0,743.976272,789.008911,132.62,57.843846,-87.587361,1.433158,5,2595.584418,2635.945527
149,Buy NASDAQ100 Index,200.0,172.300016,156.357725,67.67,-15.327576,-83.612290,0.340135,20,10131.283997,10086.220784
71,Buy Gold,200.0,167.560462,214.170586,126.14,49.222307,-79.529876,2.204440,20,1520.209048,1542.537761
262,Buy NASDAQ100 Index,1000.0,855.069923,779.369242,3.69,-72.254750,-79.390681,1.678345,20,10189.440742,10146.389551
241,Buy NASDAQ100 Index,1009.0,862.765553,780.957160,-2.69,-78.362461,-79.118392,1.678164,20,10282.258582,10235.563229
98,"Buy Tesla Motors, Inc.",300.0,254.243967,515.071767,338.74,265.142862,-77.912201,1.480166,2,343.534449,522.664939
148,Buy SPX500 Index,200.0,172.300016,123.942125,29.13,-47.837091,-77.487890,1.158259,20,2975.371436,2934.070577

In [109]:
df_eur_buy_trimmed[30:40].transpose()

,30,31,32,33,34,35,36,37,38,39
Position ID,834270366,834270428,834297442,827517974,827525612,826658124,827515700,826537475,827520089,829314069
Action,Buy DJ30 Index,Buy SPX500 Index,Buy US Dollar Index,Buy Meta Platforms Inc,Buy Amazon.com Inc,Buy Gold,Buy Gold,Buy Silver,Buy Silver,Buy Meta Platforms Inc
Amount,200.0,200.0,200.0,200.0,500.0,200.0,100.0,200.0,200.0,100.0
Amount_open_Eur,164.649979,164.649979,164.649979,165.646011,414.115028,165.646011,82.823006,165.646011,165.646011,82.77899
Close_amount_eur,134.206491,140.788641,158.105216,151.498755,453.132109,135.81814,74.998565,140.151071,158.631389,74.481583
Units,0.132178,1.079497,22.187708,3.619647,0.802878,2.17206,1.090721,83.022001,83.963056,1.803622
Leverage,20,20,10,5,5,20,20,10,10,5
Open Date,2020-12-16 09:08:30,2020-12-16 09:08:43,2020-12-16 09:47:43,2020-12-09 19:52:33,2020-12-09 19:56:58,2020-12-09 17:31:03,2020-12-09 19:51:10,2020-12-09 16:56:53,2020-12-09 19:53:37,2020-12-10 20:20:15
Date_x,2020-12-16 00:00:00,2020-12-16 00:00:00,2020-12-16 00:00:00,2020-12-09 00:00:00,2020-12-09 00:00:00,2020-12-09 00:00:00,2020-12-09 00:00:00,2020-12-09 00:00:00,2020-12-09 00:00:00,2020-12-10 00:00:00
Close Date,2020-12-17 07:30:18,2020-12-17 07:11:43,2020-12-16 18:49:07,2020-12-29 18:05:31,2020-12-17 20:55:33,2020-12-10 13:06:17,2020-12-10 13:06:17,2020-12-10 13:05:52,2020-12-10 13:05:52,2020-12-29 18:05:23
Date_y,2020-12-17 00:00:00,2020-12-17 00:00:00,2020-12-16 00:00:00,2020-12-29 00:00:00,2020-12-17 00:00:00,2020-12-10 00:00:00,2020-12-10 00:00:00,2020-12-10 00:00:00,2020-12-10 00:00:00,2020-12-29 00:00:00
Open Rate,30262.25,3705.43,90.14,276.27,3113.7,1841.57,1833.65,24.09,23.82,277.22
Open Rate_Eur,24913.394111,3050.494856,74.207745,228.815118,2578.859925,1525.243624,1518.684042,19.952062,19.72844,229.479916
Spread,0.79,0.76,0.89,1.81,4.68,0.98,0.49,4.15,4.2,0.9
Spread_Eur,0.647942,0.623337,0.732692,1.481177,3.838441,0.811234,0.405617,3.435328,3.476718,0.736497
Close Rate,30277.45,3714.61,90.31,277.58,3232.46,1838.58,1838.58,23.94,23.94,277.51
Close Rate_Eur,24690.083992,3029.120117,73.945795,226.116183,2635.945527,1512.231392,1512.231392,19.690641,19.690641,226.059161
Profit,2.01,9.91,3.77,4.74,95.35,-6.49,5.38,-12.45,10.08,0.52
profit_1_eur,-29.516685,-23.073966,-5.81207,-9.769191,45.832774,-28.263348,-7.03804,-21.703662,-3.173677,-6.169749
real_profit_eur,-30.443488,-23.861338,-6.544763,-14.147256,39.017081,-29.827871,-7.824441,-25.49494,-7.014622,-8.297407
Rollover Fees and Dividends,-0.34,-0.2,0.0,-3.54,-3.63,-0.91,-0.46,-0.43,-0.44,-1.7
Fee_Eur,-0.278861,-0.164036,0.0,-2.896888,-2.977252,-0.753289,-0.380783,-0.35595,-0.364228,-1.391161
diff_rates,-223.310119,-21.374738,-0.26195,-2.698935,57.085602,-13.012232,-6.45265,-0.261421,-0.037798,-3.420755

In [106]:
df_trimmed[19:40]

,Action,Amount,Amount_open_Eur,Close_amount_eur,Units,Leverage,Open Rate_Eur,Close Rate_Eur,Profit,profit_1_eur
19,Buy Platinum,100.0,82.324989,29.000724,0.949487,10,867.046789,814.080653,-54.31,-50.290657
20,Buy Nickel Future Contract,100.0,82.324989,74.758597,0.057216,10,14388.350026,14280.763272,2.00,-6.155684
21,Buy Copper,100.0,82.324989,83.215270,280.426248,10,2.939002,2.943815,11.22,1.349581
22,Buy Silver,100.0,82.324989,90.236608,39.323634,10,20.935245,21.177526,21.23,9.527373
23,Buy Silver,100.0,82.324989,104.702509,40.016006,10,20.573015,21.177526,39.22,24.190117
24,Buy Silver,100.0,82.324989,105.721068,40.064103,10,20.548317,21.177526,40.46,25.208675
25,Buy Silver,200.0,164.649979,199.987396,79.586152,10,20.688270,21.177526,66.85,38.938006
26,Buy Gold,200.0,164.649979,179.094793,2.144807,20,1535.336355,1542.770937,57.76,15.945743
27,Buy Gold,100.0,82.324989,91.609216,1.073508,20,1533.755715,1542.770937,30.97,9.677912
28,Buy Gold,100.0,82.324989,99.350652,1.078760,20,1526.288839,1542.770937,40.91,17.780228
29,Buy Gold,100.0,82.324989,92.332882,1.074206,20,1532.759583,1542.770937,32.29,10.754256
30,Buy DJ30 Index,200.0,164.649979,134.206491,0.132178,20,24913.394111,24690.083992,2.01,-29.516685
31,Buy SPX500 Index,200.0,164.649979,140.788641,1.079497,20,3050.494856,3029.120117,9.91,-23.073966
32,Buy US Dollar Index,200.0,164.649979,158.105216,22.187708,10,74.207745,73.945795,3.77,-5.812070
33,Buy Meta Platforms Inc,200.0,165.646011,151.498755,3.619647,5,228.815118,226.116183,4.74,-9.769191
34,Buy Amazon.com Inc,500.0,414.115028,453.132109,0.802878,5,2578.859925,2635.945527,95.35,45.832774
35,Buy Gold,200.0,165.646011,135.818140,2.172060,20,1525.243624,1512.231392,-6.49,-28.263348
36,Buy Gold,100.0,82.823006,74.998565,1.090721,20,1518.684042,1512.231392,5.38,-7.038040
37,Buy Silver,200.0,165.646011,140.151071,83.022001,10,19.952062,19.690641,-12.45,-21.703662
38,Buy Silver,200.0,165.646011,158.631389,83.963056,10,19.728440,19.690641,10.08,-3.173677
39,Buy Meta Platforms Inc,100.0,82.778990,74.481583,1.803622,5,229.479916,226.059161,0.52,-6.169749

In [103]:
df_profits = df_eur_buy[['Profit','profit_1_eur','real_profit_eur']]

In [108]:
df_eur_buy_trimmed[19:40]

,Position ID,Action,Amount,Amount_open_Eur,Close_amount_eur,Units,Leverage,Open Date,Date_x,Close Date,...,Spread,Spread_Eur,Close Rate,Close Rate_Eur,Profit,profit_1_eur,real_profit_eur,Rollover Fees and Dividends,Fee_Eur,diff_rates
19,834301848,Buy Platinum,100.0,82.324989,29.000724,0.949487,10,2020-12-16 10:00:58,2020-12-16,2020-12-21 10:02:09,...,3.32,2.736842,996.00,814.080653,-54.31,-50.290657,-53.324265,-0.36,-0.296766,-52.966136
20,834296756,Buy Nickel Future Contract,100.0,82.324989,74.758597,0.057216,10,2020-12-16 09:45:37,2020-12-16,2020-12-17 15:04:24,...,1.72,1.410709,17512.50,14280.763272,2.00,-6.155684,-7.566393,0.00,0.000000,-107.586754
21,834296513,Buy Copper,100.0,82.324989,83.215270,280.426248,10,2020-12-16 09:45:24,2020-12-16,2020-12-17 15:03:18,...,0.56,0.459301,3.61,2.943815,11.22,1.349581,0.890280,0.00,0.000000,0.004813
22,835744674,Buy Silver,100.0,82.324989,90.236608,39.323634,10,2020-12-16 21:02:17,2020-12-16,2020-12-17 14:58:51,...,1.97,1.615754,25.97,21.177526,21.23,9.527373,7.911619,0.00,0.000000,0.242281
23,834270067,Buy Silver,100.0,82.324989,104.702509,40.016006,10,2020-12-16 09:08:00,2020-12-16,2020-12-17 14:58:50,...,2.00,1.640359,25.97,21.177526,39.22,24.190117,22.377520,-0.21,-0.172238,0.604511
24,835483761,Buy Silver,100.0,82.324989,105.721068,40.064103,10,2020-12-16 17:49:17,2020-12-16,2020-12-17 14:58:50,...,2.00,1.640359,25.97,21.177526,40.46,25.208675,23.396078,-0.21,-0.172238,0.629209
25,834298821,Buy Silver,200.0,164.649979,199.987396,79.586152,10,2020-12-16 09:51:58,2020-12-16,2020-12-17 14:58:50,...,3.98,3.264315,25.97,21.177526,66.85,38.938006,35.337417,-0.41,-0.336274,0.489256
26,834299807,Buy Gold,200.0,164.649979,179.094793,2.144807,20,2020-12-16 09:54:40,2020-12-16,2020-12-17 14:58:41,...,0.97,0.795574,1891.90,1542.770937,57.76,15.945743,14.444814,-0.86,-0.705355,7.434582
27,835746835,Buy Gold,100.0,82.324989,91.609216,1.073508,20,2020-12-16 21:13:56,2020-12-16,2020-12-17 14:58:41,...,0.48,0.393686,1891.90,1542.770937,30.97,9.677912,9.284226,0.00,0.000000,9.015222
28,835481696,Buy Gold,100.0,82.324989,99.350652,1.078760,20,2020-12-16 17:47:49,2020-12-16,2020-12-17 14:58:40,...,0.49,0.401888,1891.90,1542.770937,40.91,17.780228,17.025663,-0.43,-0.352677,16.482098
29,834270115,Buy Gold,100.0,82.324989,92.332882,1.074206,20,2020-12-16 09:08:10,2020-12-16,2020-12-17 14:58:40,...,0.48,0.393686,1891.90,1542.770937,32.29,10.754256,10.007893,-0.43,-0.352677,10.011354
30,834270366,Buy DJ30 Index,200.0,164.649979,134.206491,0.132178,20,2020-12-16 09:08:30,2020-12-16,2020-12-17 07:30:18,...,0.79,0.647942,30277.45,24690.083992,2.01,-29.516685,-30.443488,-0.34,-0.278861,-223.310119
31,834270428,Buy SPX500 Index,200.0,164.649979,140.788641,1.079497,20,2020-12-16 09:08:43,2020-12-16,2020-12-17 07:11:43,...,0.76,0.623337,3714.61,3029.120117,9.91,-23.073966,-23.861338,-0.20,-0.164036,-21.374738
32,834297442,Buy US Dollar Index,200.0,164.649979,158.105216,22.187708,10,2020-12-16 09:47:43,2020-12-16,2020-12-16 18:49:07,...,0.89,0.732692,90.31,73.945795,3.77,-5.812070,-6.544763,0.00,0.000000,-0.261950
33,827517974,Buy Meta Platforms Inc,200.0,165.646011,151.498755,3.619647,5,2020-12-09 19:52:33,2020-12-09,2020-12-29 18:05:31,...,1.81,1.481177,277.58,226.116183,4.74,-9.769191,-14.147256,-3.54,-2.896888,-2.698935
34,827525612,Buy Amazon.com Inc,500.0,414.115028,453.132109,0.802878,5,2020-12-09 19:56:58,2020-12-09,2020-12-17 20:55:33,...,4.68,3.838441,3232.46,2635.945527,95.35,45.832774,39.017081,-3.63,-2.977252,57.085602
35,826658124,Buy Gold,200.0,165.646011,135.818140,2.172060,20,2020-12-09 17:31:03,2020-12-09,2020-12-10 13:06:17,...,0.98,0.811234,1838.58,1512.231392,-6.49,-28.263348,-29.827871,-0.91,-0.753289,-13.012232
36,827515700,Buy Gold,100.0,82.823006,74.998565,1.090721,20,2020-12-09 19:51:10,2020-12-09,2020-12-10 13:06:17,...,0.49,0.405617,1838.58,1512.231392,5.38,-7.038040,-7.824441,-0.46,-0.380783,-6.452650
37,826537475,Buy Silver,200.0,165.646011,140.151071,83.022001,10,2020-12-09 16:56:53,2020-12-09,2020-12-10 13:05:52,...,4.15,3.435328,23.94,19.690641,-12.45,-21.703662,-25.494940,-0.43,-0.355950,-0.261421
38,827520089,Buy Silver,200.0,165.646011,158.631389,83.963056,10,2020-12-09 19:53:37,2020-12-09,2020-12-10 13:05:52,...,4.20,3.476718,23.94,19.690641,10.08,-3.173677,-7.014622,-0.44,-0.364228,-0.037798
39,829314069,Buy Meta Platforms Inc,100.0,82.778990,74.481583,1.803622,5,2020-12-10 20:20:15,2020-12-10,2020-12-29 18:05:23,...,0.90,0.736497,277.51,226.059161,0.52,-6.169749,-8.297407,-1.70,-1.391161,-3.420755

In [86]:
df_eur_buy['profit_1_eur'].sum()

-9724.9576969144

In [81]:
df_eur_buy['real_profit_eur'].sum()

-10499.870648890237

In [98]:
df_eur_buy_trimmed['Profit'].sum()

-399.7899999999995

In [79]:
df_eur_buy.iloc[:,0:12]

,Position ID,ActionType,Action,Amount,Units,Leverage,Open Date,Open Rate,Date_x,Open_x,High_x,Low_x
0,845829079,Buy,Buy Meta Platforms Inc,100.00,1.875610,5,2020-12-22 20:52:51,266.58,2020-12-22,1.223840,1.225900,1.216604
1,845839951,Buy,Buy Meta Platforms Inc,100.00,1.870487,5,2020-12-22 20:56:19,267.31,2020-12-22,1.223840,1.225900,1.216604
2,845060804,Buy,Buy Meta Platforms Inc,100.00,1.850687,5,2020-12-22 15:10:16,270.17,2020-12-22,1.223840,1.225900,1.216604
3,845849795,Buy,Buy Amazon.com Inc,200.00,0.311589,5,2020-12-22 20:59:24,3209.36,2020-12-22,1.223840,1.225900,1.216604
4,845843260,Buy,Buy Amazon.com Inc,200.00,0.311569,5,2020-12-22 20:57:55,3209.56,2020-12-22,1.223840,1.225900,1.216604
...,...,...,...,...,...,...,...,...,...,...,...,...
370,755538722,Buy,"Buy Tesla Motors, Inc.",48.58,0.568402,5,2020-10-06 13:33:53,427.38,2020-10-06,1.178828,1.180735,1.176734
371,755378788,Buy,"Buy Tesla Motors, Inc.",49.99,0.584893,5,2020-10-06 13:33:53,427.38,2020-10-06,1.178828,1.180735,1.176734
372,753535508,Buy,"Buy Tesla Motors, Inc.",49.81,0.582711,5,2020-10-06 13:33:53,427.38,2020-10-06,1.178828,1.180735,1.176734
373,753535233,Buy,"Buy Tesla Motors, Inc.",49.95,0.584344,5,2020-10-06 13:33:53,427.38,2020-10-06,1.178828,1.180735,1.176734
374,753749828,Buy,Buy SPX500 Index,201.00,1.173014,20,2020-10-08 08:36:03,3427.07,2020-10-08,1.176554,1.178134,1.173530

In [116]:
for i in range(5):
  for j in range(i):
    if j %2 == 0:
      print (j)

0
0
0
2
0
2