<a href="https://colab.research.google.com/github/VijayTaori/Lifo_step1/blob/main/Copy_of_Detailed_lifo_Aave.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import datetime as dt
import time
import calendar
df_open = pd.read_csv('/content/et_open_alldata.csv')
df_close = pd.read_csv('/content/et_close_alldata.csv')
df_close['Close Datetime'] = pd.to_datetime(df_close['Close_unix_timestamp'],dayfirst=True,unit='s')
df_open['Open Datetime'] = pd.to_datetime(df_open['Open_unix_timestamp'],dayfirst=True,unit='s')
df_close_btc = df_close[df_close['Close Action'] =='Buy Aave']
df_open_btc = df_open[df_open['Open Action'] =='Buy Aave']
df_close_btc_original = df_close_btc
df_open_btc_original = df_open_btc
df_close_btc.reset_index(inplace=True)
df_close_btc = df_close_btc.drop('index', axis=1)
df_close_btc.reset_index(inplace=True)
df_close_btc.rename(columns={'index':'Original_Close_index'},inplace=True)
df_open_btc.reset_index(inplace=True)
df_open_btc = df_open_btc.drop('index', axis=1)
df_open_btc.reset_index(inplace=True)
df_open_btc.rename(columns={'index':'Original_Open_index'},inplace=True)
data_btc = {}
df_lifo_btc = pd.DataFrame(data_btc, 
                           columns=['Original_Open_index','Original_Close_index',
                                    'Open Position ID', 'Close Position ID',
                                    'Open Units','Close Units','Spread_Eur',
                                    'Open Amount_Eur','Amount_close_Eur',
                                    'Open Datetime', 'Close Datetime',
                                    'Open Rate_Eur', 'Close Rate_Eur',
                                    'Open Action', 'Close Action', 
                                    'Open Amount','Close Rate', 'Open Rate',
                                    'Close Spread', 'Close Profit USD',
                                    'Close_Date','Open_Date',
                                    'Close_unix_timestamp','EurOpen_y', 
                                    'EurHigh_y','EurLow_y', 'EurClose_y',
                                    'EurWeekday_y', 'Open_unix_timestamp',
                                    'EurOpen_x', 'EurHigh_x','EurLow_x', 
                                    'EurClose_x','EurWeekday_x'
                                    ]
                           )

In [ ]:
df_close['Close Action'].unique()

array(['Buy Bitcoin', 'Buy Ethereum', 'Buy XRP', 'Buy Tezos', 'Buy EOS',
       'Buy Cardano', 'Buy Litecoin', 'Buy Build and Build', 'Buy TRON',
       'Buy Dogecoin', 'Buy Chainlink', 'Buy Uniswap', 'Buy Polygon',
       'Buy Stellar', 'Buy Decentraland', 'Buy Aave', 'Buy IOTA',
       'Buy Shiba (in millions)', 'Buy Enjin', 'Buy Maker',
       'Buy Algorand', 'Buy Solana', 'Buy Polkadot', 'Buy Songbird'],
      dtype=object)

In [ ]:
df_open[df_open['Open Datetime'] == pd.NaT]

Empty DataFrame
Columns: [Open Position ID, Open Action, Open Amount, Open Units, Open Datetime, Open Rate, Open_Date, Open_unix_timestamp, EurOpen_x, EurHigh_x, EurLow_x, EurClose_x, EurWeekday_x, Open Amount_Eur, Open Rate_Eur]
Index: []

In [ ]:
df_close[df_close['Close Datetime'] == pd.NaT]

Empty DataFrame
Columns: [Close Position ID, Close Action, Close Units, Close Datetime, Close Rate, Close Spread, Close Profit USD, Close_Date, Close_unix_timestamp, EurOpen_y, EurHigh_y, EurLow_y, EurClose_y, EurWeekday_y, Close Rate_Eur, Amount_close_Eur, Spread_Eur]
Index: []

In [ ]:
# Let's build a index selector for df_close_btc
close_unit_index = 0
value_close_units = df_close_btc.loc[close_unit_index, 'Close Units']
final_close_unit_index = df_open_btc.shape[0]
fruit_list = list(range(400))
serial_number_for_loop = 0
serial_number_if_loop = 0
serial_number_elif_loop_1 = 0
serial_number_elif_loop_2 = 0
serial_number_else_loop = 0
for x in fruit_list:#while close_unit_index < final_close_unit_index:
  serial_number_for_loop = serial_number_for_loop + 1
  print('For loop run number:',serial_number_for_loop)
  i = 0
  #if value_close_units == 0:
  #  i = 1
  #else:
  #  i = 0
  print('i =',i)
  close_unit_index = close_unit_index + i
  value_close_units = df_close_btc.loc[close_unit_index, 'Close Units']
  # How to set up an upper limit on this variable?? use df.shape[0]
  # Choosing first row from df_close_btc where the units are = values_of_units
  # Assign it as new DF
  # change the reset the index and the drop the 'index' column
  df_latest_row_from_close = df_close_btc[close_unit_index:(close_unit_index+1)]
  df_latest_row_from_close.reset_index(inplace=True)
  current_close_index = df_latest_row_from_close.at[0,'index']
  df_latest_row_from_close = df_latest_row_from_close.drop('index',axis=1)
  # Get the datetime value from the df_latest_row_from_close
  close_unit_datetime = df_close_btc.loc[close_unit_index,'Close Datetime']
  print('close_unit_datetime:',close_unit_datetime)
  # find all the transaction datetimes from df_open that were opened before the close_unit_datetime
  open_datetimes_b4 = df_open_btc['Open Datetime'][df_open_btc['Open Datetime'] < close_unit_datetime]
  #Latest datetime beofore close datetime
  open_datetime_lifo = open_datetimes_b4.max()
  #if open_datetime_lifo == pd.NaT:
  #  break
  #else:
  #  continue
  print('open_datetime_lifo:',open_datetime_lifo)
  '''
  Remember that even if only one value for open_datetime_lifo is chosen
  this can still result in chosing more than one rows in that case last row 
  should be chosen
  '''
  # Corresponding row for the open_datetime_lifo 
  # let's make a new DF
  df_latest_last_row_open = df_open_btc[df_open_btc['Open Datetime'] == open_datetime_lifo]
  df_latest_last_row_open = df_latest_last_row_open[::-1]
  df_latest_last_row_open = df_latest_last_row_open[0:1]
  df_latest_last_row_open.reset_index(inplace=True)
  current_open_index = df_latest_last_row_open.at[0,'index']
  df_latest_last_row_open = df_latest_last_row_open.drop('index', axis=1)
  value_open_units = df_latest_last_row_open.loc[0,'Open Units']
  print('value_close_units:',value_close_units, 'value_open_units:',value_open_units)
  abs_diff_open_close_units = abs(value_close_units - value_open_units)
  print('abs_diff_open_close_units:',abs_diff_open_close_units)
  value_open_amount = df_latest_last_row_open.loc[0,'Open Amount_Eur']
  value_close_amount = df_latest_row_from_close.loc[0,'Amount_close_Eur']
  value_close_spread_eur = df_latest_row_from_close.loc[0,'Spread_Eur']
  close_Rate_eur = df_latest_row_from_close.loc[0,'Close Rate_Eur']
  open_Rate_eur = df_latest_last_row_open.loc[0,'Open Rate_Eur']
  #Remember that 'Open_index' and 'Close_index' columns host original indices
  # This is important as df_open_btc starts to drop rows the original indices will come in handy 
  # And in case of df_close_btc this should remain equal to the indices from DataFrame
  original_open_index = df_latest_last_row_open.at[0, 'Original_Open_index']
  #Remeber that earlier defined close_unit_index is the index of units from df_close_btc DataFrame
  # close_index should essentially be equal in integer value of close_unit_index
  close_index = df_latest_row_from_close.at[0, 'Original_Close_index']
  is_it_equal = close_unit_index == close_index
  print('(close_unit_index = close_index) is:',is_it_equal)
  if value_close_units > value_open_units:
    serial_number_if_loop = serial_number_if_loop + 1
    print('If_loop run number:',serial_number_if_loop)
    #First lets extract all the values from open DF df_latest_last_row_open
    newth_list_open_half = df_latest_last_row_open.to_dict('records')
    newth_dict_open_half = newth_list_open_half[0]
    #Then permanently delete the first row of the open DF df_latest_last_row_open from df_open_btc
    df_open_btc = df_open_btc.drop(current_open_index,axis=0)
    #Then reset index and drop the new column 'index' in df_open_btc
    df_open_btc.reset_index(inplace=True)
    df_open_btc = df_open_btc.drop('index',axis=1)
    #Now lets work on the Close_side
    #First define the changed values for df_latest_row_from_close
    changed_value_close_units = value_open_units
    changed_value_close_amount = changed_value_close_units * close_Rate_eur
    changed_value_close_spread = changed_value_close_units * value_close_spread_eur/value_close_units
    #First change the values of 'units' and 'amount' and 'spread' in the df_latest_row_from_close
    # These values will be reported
    df_latest_row_from_close.at[0,'Close Units'] = changed_value_close_units
    df_latest_row_from_close.at[0,'Amount_close_Eur'] = changed_value_close_amount
    df_latest_row_from_close.at[0,'Spread_Eur'] = changed_value_close_spread
    # Now lets extract all the values from df_latest_row_from_close
    newth_list_close_half = df_latest_row_from_close.to_dict('records')
    newth_dict_close_half = newth_list_close_half[0]
    newth_whole_dict = {**newth_dict_open_half,**newth_dict_close_half}
    # Now append the newth_whole_dict to the new records DataFrame df_lifo_btc
    df_lifo_btc = df_lifo_btc.append(newth_whole_dict, ignore_index=True)
    # and after that change the value of units and amount in original df_open_btc
    df_close_btc.at[close_unit_index,'Close Units'] = value_close_units - changed_value_close_units
    df_close_btc.at[close_unit_index,'Amount_close_Eur'] = value_close_amount - changed_value_close_amount
    df_close_btc.at[close_unit_index,'Spread_Eur'] = value_close_spread_eur - changed_value_close_spread
    print('value_close_units:',value_close_units)
    print('value_open_units:',value_open_units)
    print('close_unit_index:',close_unit_index)
    print('If_loop run number:',serial_number_if_loop,'finished')
  elif value_close_units < value_open_units:
    serial_number_elif_loop_1 = serial_number_elif_loop_1 + 1
    print('Elif_loop_1 run number:', serial_number_elif_loop_1)
    ## First lets extract all the values form close DF df_latest_row_from_close
    newth_list_close_half = df_latest_row_from_close.to_dict('records')
    newth_dict_close_half = newth_list_close_half[0]
    #First define the changed values for df_latest_row_from_close
    ## In elif statement changed values are same as we made only one change
    changed_value_close_units = value_close_units # value_open_units in if statement was here change to value_close_unit
    changed_value_close_amount = changed_value_close_units * close_Rate_eur
    changed_value_close_spread = changed_value_close_units * value_close_spread_eur/value_close_units
    # and after that change the value of units and amount and spread in original df_close_btc
    df_close_btc.at[close_unit_index,'Close Units'] = value_close_units - changed_value_close_units
    df_close_btc.at[close_unit_index,'Amount_close_Eur'] = value_close_amount - changed_value_close_amount
    df_close_btc.at[close_unit_index,'Spread_Eur'] = value_close_spread_eur - changed_value_close_spread
    #First change the values of 'units' and 'amount' and 'spread' in the df_latest_row_from_close
    # These values will be reported
    df_latest_row_from_close.at[0,'Close Units'] = changed_value_close_units
    df_latest_row_from_close.at[0,'Amount_close_Eur'] = changed_value_close_amount
    df_latest_row_from_close.at[0,'Spread_Eur'] = changed_value_close_spread
    # Now lets extract all the values from df_latest_row_from_close
    ## Now lets work on the values from open DF df_latest_last_row_lifo
    ## Remember we want to get back the values in the df_latest_row_from_close 
    ## we will have to assign changed_values for open_units and open_amount
    changed_value_open_units = value_close_units
    changed_value_open_amount = changed_value_open_units * open_Rate_eur
    df_latest_last_row_open.at[0,'Open Units'] = changed_value_close_units
    df_latest_last_row_open.at[0,'Open Amount_Eur'] = changed_value_close_amount
    ##After the values are changed extract the values which will then be reported
    newth_list_open_half = df_latest_last_row_open.to_dict('records')
    newth_dict_open_half = newth_list_open_half[0]
    ## and then this time change the original values in the df_open_units
    newth_whole_dict = {**newth_dict_open_half,**newth_dict_close_half}
    # Now append the newth_whole_dict to the new records DataFrame df_lifo_btc
    df_lifo_btc = df_lifo_btc.append(newth_whole_dict, ignore_index=True)
    # and after that change the value of units and amount in original df_open_btc
    df_open_btc.at[current_open_index,'Open Units'] = value_open_units - changed_value_open_units
    df_open_btc.at[current_open_index,'Open Amount_Eur'] = value_open_amount - changed_value_open_amount
    print('value_close_units:',value_close_units)
    print('value_open_units:',value_open_units)
    print('close_unit_index:',close_unit_index)
    print('Elif_loop_1 run number:', serial_number_elif_loop_1, 'finished')
  elif value_close_units == value_open_units:
    serial_number_elif_loop_2 = serial_number_elif_loop_2 + 1
    if value_close_units == 0:
      print('We are running value_close_units == 0 condition')
      print('This is in the Elif_loop_number_2:',serial_number_elif_loop_2)
      #Then permanently delete the first row of the open DF df_latest_last_row_open from df_open_btc
      df_open_btc = df_open_btc.drop(current_open_index,axis=0)
      #Then reset index and drop the new column 'index' in df_open_btc
      df_open_btc.reset_index(inplace=True)
      df_open_btc = df_open_btc.drop('index',axis=1)
      print('We are breaking')
      break
    else:
      #First lets extract all the values from open DF df_latest_last_row_open
      newth_list_open_half = df_latest_last_row_open.to_dict('records')
      newth_dict_open_half = newth_list_open_half[0]
      #Then permanently delete the first row of the open DF df_latest_last_row_open from df_open_btc
      df_open_btc = df_open_btc.drop(current_open_index,axis=0)
      #Then reset index and drop the new column 'index' in df_open_btc
      df_open_btc.reset_index(inplace=True)
      df_open_btc = df_open_btc.drop('index',axis=1)
      ### Second lets extract all the values form close DF df_latest_row_from_close
      newth_list_close_half = df_latest_row_from_close.to_dict('records')
      newth_dict_close_half = newth_list_close_half[0]
      #First define the changed values for df_latest_row_from_close
      changed_value_close_units = value_open_units
      changed_value_close_amount = changed_value_close_units * close_Rate_eur
      changed_value_close_spread = changed_value_close_units * value_close_spread_eur/value_close_units
      # and after that change the value of units and amount in original df_open_btc
      df_close_btc.at[close_unit_index,'Close Units'] = value_close_units - changed_value_close_units
      df_close_btc.at[close_unit_index,'Amount_close_Eur'] = value_close_amount - changed_value_close_amount
      df_close_btc.at[close_unit_index,'Spread_Eur'] = value_close_spread_eur - changed_value_close_spread
    print('value_close_units:',value_close_units)
    print('value_open_units:',value_open_units)
    print('close_unit_index:',close_unit_index)
    print('Elif_loop_2 run number:', serial_number_elif_loop_2, 'finished')
  else:
    serial_number_else_loop = serial_number_else_loop + 1
    print('Do we need to write more code? The answer is a: BIG YES!!')
    print('Or on second thought this is a silly mistake!!!')
    print('value_close_units:',value_close_units)
    print('value_open_units:',value_open_units)
    print('close_unit_index:',close_unit_index)
    print('serial_number_else_loop:', serial_number_else_loop, 'finished')
    print('We are breaking here!!')
    break
  value_close_units = df_close_btc.loc[close_unit_index, 'Close Units']
  if value_close_units == 0:
    i = 1
  else:
    i = 0
  print('i =',i)
  close_unit_index = close_unit_index + i
  print('For loop run number:',serial_number_for_loop,'finished')
  print('****************************************')

For loop run number: 1
i = 0
close_unit_datetime: 2021-10-25 09:37:35
open_datetime_lifo: 2021-09-24 10:37:48
value_close_units: 3.225226 value_open_units: 2.060082
abs_diff_open_close_units: 1.1651440000000002
(close_unit_index = close_index) is: True
If_loop run number: 1
value_close_units: 3.225226
value_open_units: 2.060082
close_unit_index: 0
If_loop run number: 1 finished
i = 0
For loop run number: 1 finished
****************************************
For loop run number: 2
i = 0
close_unit_datetime: 2021-10-25 09:37:35
open_datetime_lifo: 2021-09-24 10:37:48
value_close_units: 1.1651440000000002 value_open_units: 2.130635
abs_diff_open_close_units: 0.9654909999999997
(close_unit_index = close_index) is: True
Elif_loop_1 run number: 1
value_close_units: 1.1651440000000002
value_open_units: 2.130635
close_unit_index: 0
Elif_loop_1 run number: 1 finished
i = 1
For loop run number: 2 finished
****************************************
For loop run number: 3
i = 0
close_unit_datetime: 2021-10-26 06:43:10
open_datetime_lifo: 2021-09-24 10:37:48
value_close_units: 1.912817 value_open_units: 0.9654909999999997
abs_diff_open_close_units: 0.9473260000000003
(close_unit_index = close_index) is: True
If_loop run number: 2
value_close_units: 1.912817
value_open_units: 0.9654909999999997
close_unit_index: 1
If_loop run number: 2 finished
i = 0
For loop run number: 3 finished
****************************************
For loop run number: 4
i = 0
close_unit_datetime: 2021-10-26 06:43:10
open_datetime_lifo: 2021-09-24 10:37:48
value_close_units: 0.9473260000000003 value_open_units: 0.070552
abs_diff_open_close_units: 0.8767740000000004
(close_unit_index = close_index) is: True
If_loop run number: 3
value_close_units: 0.9473260000000003
value_open_units: 0.070552
close_unit_index: 1
If_loop run number: 3 finished
i = 0
For loop run number: 4 finished
****************************************
For loop run number: 5
i = 0
close_unit_datetime: 2021-10-26 06:43:10
open_datetime_lifo: 2021-09-24 06:29:17
value_close_units: 0.8767740000000004 value_open_units: 1.912817
abs_diff_open_close_units: 1.0360429999999996
(close_unit_index = close_index) is: True
Elif_loop_1 run number: 2
value_close_units: 0.8767740000000004
value_open_units: 1.912817
close_unit_index: 1
Elif_loop_1 run number: 2 finished
i = 1
For loop run number: 5 finished
****************************************
For loop run number: 6
i = 0
close_unit_datetime: 2021-10-27 07:45:19
open_datetime_lifo: 2021-09-24 06:29:17
value_close_units: 1.912817 value_open_units: 1.0360429999999996
abs_diff_open_close_units: 0.8767740000000004
(close_unit_index = close_index) is: True
If_loop run number: 4
value_close_units: 1.912817
value_open_units: 1.0360429999999996
close_unit_index: 2
If_loop run number: 4 finished
i = 0
For loop run number: 6 finished
****************************************
For loop run number: 7
i = 0
close_unit_datetime: 2021-10-27 07:45:19
open_datetime_lifo: 2021-09-24 06:29:17
value_close_units: 0.8767740000000004 value_open_units: 1.912817
abs_diff_open_close_units: 1.0360429999999996
(close_unit_index = close_index) is: True
Elif_loop_1 run number: 3
value_close_units: 0.8767740000000004
value_open_units: 1.912817
close_unit_index: 2
Elif_loop_1 run number: 3 finished
i = 1
For loop run number: 7 finished
****************************************
For loop run number: 8
i = 0
close_unit_datetime: 2021-10-27 08:22:00
open_datetime_lifo: 2021-09-24 06:29:17
value_close_units: 3.319542 value_open_units: 1.0360429999999996
abs_diff_open_close_units: 2.283499000000001
(close_unit_index = close_index) is: True
If_loop run number: 5
value_close_units: 3.319542
value_open_units: 1.0360429999999996
close_unit_index: 3
If_loop run number: 5 finished
i = 0
For loop run number: 8 finished
****************************************
For loop run number: 9
i = 0
close_unit_datetime: 2021-10-27 08:22:00
open_datetime_lifo: 2021-09-20 20:31:36
value_close_units: 2.283499000000001 value_open_units: 3.319542
abs_diff_open_close_units: 1.0360429999999994
(close_unit_index = close_index) is: True
Elif_loop_1 run number: 4
value_close_units: 2.283499000000001
value_open_units: 3.319542
close_unit_index: 3
Elif_loop_1 run number: 4 finished
i = 1
For loop run number: 9 finished
****************************************
For loop run number: 10
i = 0
close_unit_datetime: 2021-10-27 09:09:18
open_datetime_lifo: 2021-09-20 20:31:36
value_close_units: 2.130635 value_open_units: 1.0360429999999994
abs_diff_open_close_units: 1.0945920000000005
(close_unit_index = close_index) is: True
If_loop run number: 6
value_close_units: 2.130635
value_open_units: 1.0360429999999994
close_unit_index: 4
If_loop run number: 6 finished
i = 0
For loop run number: 10 finished
****************************************
For loop run number: 11
i = 0
close_unit_datetime: 2021-10-27 09:09:18
open_datetime_lifo: 2021-09-10 13:34:54
value_close_units: 1.0945920000000005 value_open_units: 3.225226
abs_diff_open_close_units: 2.1306339999999997
(close_unit_index = close_index) is: True
Elif_loop_1 run number: 5
value_close_units: 1.0945920000000005
value_open_units: 3.225226
close_unit_index: 4
Elif_loop_1 run number: 5 finished
i = 1
For loop run number: 11 finished
****************************************
For loop run number: 12
i = 0
close_unit_datetime: 2021-10-27 09:10:32
open_datetime_lifo: 2021-09-10 13:34:54
value_close_units: 2.060082 value_open_units: 2.1306339999999997
abs_diff_open_close_units: 0.07055199999999973
(close_unit_index = close_index) is: True
Elif_loop_1 run number: 6
value_close_units: 2.060082
value_open_units: 2.1306339999999997
close_unit_index: 5
Elif_loop_1 run number: 6 finished
i = 1
For loop run number: 12 finished
****************************************
For loop run number: 13
i = 0
close_unit_datetime: 2021-12-15 19:23:10
open_datetime_lifo: 2021-10-30 14:25:37
value_close_units: 1.58613 value_open_units: 1.58613
abs_diff_open_close_units: 0.0
(close_unit_index = close_index) is: True
value_close_units: 1.58613
value_open_units: 1.58613
close_unit_index: 6
Elif_loop_2 run number: 1 finished
i = 1
For loop run number: 13 finished
****************************************
For loop run number: 14
i = 0
close_unit_datetime: 2021-12-15 19:23:16
open_datetime_lifo: 2021-09-10 13:34:54
value_close_units: 0.070552 value_open_units: 0.07055199999999973
abs_diff_open_close_units: 2.7755575615628914e-16
(close_unit_index = close_index) is: True
If_loop run number: 7
value_close_units: 0.070552
value_open_units: 0.07055199999999973
close_unit_index: 7
If_loop run number: 7 finished
i = 0
For loop run number: 14 finished
****************************************
For loop run number: 15
i = 0
close_unit_datetime: 2021-12-15 19:23:16
open_datetime_lifo: NaT

KeyError: ignored

In [ ]:
df_lifo_btc

In [ ]:
df_open_btc

Empty DataFrame
Columns: [Original_Open_index, Open Position ID, Open Action, Open Amount, Open Units, Open Datetime, Open Rate, Open_Date, Open_unix_timestamp, EurOpen_x, EurHigh_x, EurLow_x, EurClose_x, EurWeekday_x, Open Amount_Eur, Open Rate_Eur]
Index: []

In [ ]:
df_close_btc

,Original_Close_index,Close Position ID,Close Action,Close Units,Close Datetime,Close Rate,Close Spread,Close Profit USD,Close_Date,Close_unix_timestamp,EurOpen_y,EurHigh_y,EurLow_y,EurClose_y,EurWeekday_y,Close Rate_Eur,Amount_close_Eur,Spread_Eur
0,0,1306981030,Buy Aave,0.000000e+00,2021-10-25 09:37:35,304.30,39.04,-75.70,25/10/2021 00:00,1635154655,1.164131,1.166861,1.159326,1.164009,Monday,260.785132,-6.235456e-08,0.000000e+00
1,1,1362155210,Buy Aave,0.000000e+00,2021-10-26 06:43:10,322.66,24.55,31.78,26/10/2021 00:00,1635230590,1.161170,1.162900,1.158587,1.161170,Tuesday,277.461519,7.610385e-08,0.000000e+00
2,2,1321772284,Buy Aave,0.000000e+00,2021-10-27 07:45:19,366.37,27.87,115.38,27/10/2021 00:00,1635320719,1.159824,1.162439,1.158534,1.159824,Wednesday,315.173527,-6.068586e-08,0.000000e+00
3,3,1317471956,Buy Aave,0.000000e+00,2021-10-27 08:22:00,385.76,50.94,280.56,27/10/2021 00:00,1635322920,1.159824,1.162439,1.158534,1.159824,Wednesday,331.853973,8.745064e-08,0.000000e+00
4,4,1364198742,Buy Aave,0.000000e+00,2021-10-27 09:09:18,407.81,34.56,271.54,27/10/2021 00:00,1635325758,1.159824,1.162439,1.158534,1.159824,Wednesday,350.822710,1.052771e-07,1.776357e-15
5,5,1364200314,Buy Aave,0.000000e+00,2021-10-27 09:10:32,412.13,33.77,271.44,27/10/2021 00:00,1635325832,1.159824,1.162439,1.158534,1.159824,Wednesday,354.539034,-3.477976e-08,0.000000e+00
6,6,1369608920,Buy Aave,0.000000e+00,2021-12-15 19:23:10,165.16,10.42,-250.14,15/12/2021 00:00,1639596190,1.125873,1.127800,1.124923,1.126126,Wednesday,146.444405,9.735001e-08,0.000000e+00
7,7,1321899215,Buy Aave,2.775558e-16,2021-12-15 19:23:16,164.96,0.46,-8.14,15/12/2021 00:00,1639596196,1.125873,1.127800,1.124923,1.126126,Wednesday,146.267069,6.132842e-09,1.609823e-15

In [ ]:
df_lifo_btc.dtypes

In [ ]:
df_lifo_btc['time_difference'] = df_lifo_btc['Close Datetime'] - df_lifo_btc['Open Datetime']
df_lifo_btc['time_difference_days'] = df_lifo_btc['time_difference'] / np.timedelta64(1, 'D')
df_lifo_btc_taxable = df_lifo_btc[df_lifo_btc['time_difference_days'] < 365]
df_lifo_btc_taxable_2020 = df_lifo_btc_taxable[df_lifo_btc_taxable['Close_unix_timestamp'] <= 1609455599]
df_lifo_btc_taxable_2020_2021 = df_lifo_btc_taxable[df_lifo_btc_taxable['Close_unix_timestamp'] <= 1640991599]
df_lifo_btc_taxable_2021 = df_lifo_btc_taxable_2020_2021[df_lifo_btc_taxable_2020_2021['Close_unix_timestamp'] > 1609455599]
df_lifo_btc_taxable_2022 = df_lifo_btc_taxable[df_lifo_btc_taxable['Close_unix_timestamp'] > 1640991599]
print('Sum of all open positions for the year 2020 in eur:',df_lifo_btc_taxable_2020['Open Amount_Eur'].sum())
print('Sum of all closed positions for the year 2020 in eur:',df_lifo_btc_taxable_2020['Amount_close_Eur'].sum())
print('Sum of all open positions for the year 2021 in eur:',df_lifo_btc_taxable_2021['Open Amount_Eur'].sum())
print('Sum of all closed positions for the year 2021 in eur:',df_lifo_btc_taxable_2021['Amount_close_Eur'].sum())
print('Sum of all open positions for the year 2022 in eur:',df_lifo_btc_taxable_2022['Open Amount_Eur'].sum())
print('Sum of all closed positions for the year 2022 in eur:',df_lifo_btc_taxable_2022['Amount_close_Eur'].sum())

Sum of all open positions for the year 2020 in eur: 0.0
Sum of all closed positions for the year 2020 in eur: 0.0
Sum of all open positions for the year 2021 in eur: 4265.680613185345
Sum of all closed positions for the year 2021 in eur: 4564.470639823868
Sum of all open positions for the year 2022 in eur: 0.0
Sum of all closed positions for the year 2022 in eur: 0.0