<a href="https://colab.research.google.com/github/VijayTaori/Lifo_step1/blob/main/Copy_of_Detailed_lifo_Uniswap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import datetime as dt
import time
import calendar
df_open = pd.read_csv('/content/et_open_alldata.csv')
df_close = pd.read_csv('/content/et_close_alldata.csv')
df_close['Close Datetime'] = pd.to_datetime(df_close['Close_unix_timestamp'],dayfirst=True,unit='s')
df_open['Open Datetime'] = pd.to_datetime(df_open['Open_unix_timestamp'],dayfirst=True,unit='s')
df_close_btc = df_close[df_close['Close Action'] =='Buy Uniswap']
df_open_btc = df_open[df_open['Open Action'] =='Buy Uniswap']
df_close_btc_original = df_close_btc
df_open_btc_original = df_open_btc
df_close_btc.reset_index(inplace=True)
df_close_btc = df_close_btc.drop('index', axis=1)
df_close_btc.reset_index(inplace=True)
df_close_btc.rename(columns={'index':'Original_Close_index'},inplace=True)
df_open_btc.reset_index(inplace=True)
df_open_btc = df_open_btc.drop('index', axis=1)
df_open_btc.reset_index(inplace=True)
df_open_btc.rename(columns={'index':'Original_Open_index'},inplace=True)
data_btc = {}
df_lifo_btc = pd.DataFrame(data_btc, 
                           columns=['Original_Open_index','Original_Close_index',
                                    'Open Position ID', 'Close Position ID',
                                    'Open Units','Close Units','Spread_Eur',
                                    'Open Amount_Eur','Amount_close_Eur',
                                    'Open Datetime', 'Close Datetime',
                                    'Open Rate_Eur', 'Close Rate_Eur',
                                    'Open Action', 'Close Action', 
                                    'Open Amount','Close Rate', 'Open Rate',
                                    'Close Spread', 'Close Profit USD',
                                    'Close_Date','Open_Date',
                                    'Close_unix_timestamp','EurOpen_y', 
                                    'EurHigh_y','EurLow_y', 'EurClose_y',
                                    'EurWeekday_y', 'Open_unix_timestamp',
                                    'EurOpen_x', 'EurHigh_x','EurLow_x', 
                                    'EurClose_x','EurWeekday_x'
                                    ]
                           )

In [ ]:
df_close['Close Action'].unique()

array(['Buy Bitcoin', 'Buy Ethereum', 'Buy XRP', 'Buy Tezos', 'Buy EOS',
       'Buy Cardano', 'Buy Litecoin', 'Buy Build and Build', 'Buy TRON',
       'Buy Dogecoin', 'Buy Chainlink', 'Buy Uniswap', 'Buy Polygon',
       'Buy Stellar', 'Buy Decentraland', 'Buy Aave', 'Buy IOTA',
       'Buy Shiba (in millions)', 'Buy Enjin', 'Buy Maker',
       'Buy Algorand', 'Buy Solana', 'Buy Polkadot', 'Buy Songbird'],
      dtype=object)

In [ ]:
df_open[df_open['Open Datetime'] == pd.NaT]

Empty DataFrame
Columns: [Open Position ID, Open Action, Open Amount, Open Units, Open Datetime, Open Rate, Open_Date, Open_unix_timestamp, EurOpen_x, EurHigh_x, EurLow_x, EurClose_x, EurWeekday_x, Open Amount_Eur, Open Rate_Eur]
Index: []

In [ ]:
df_close[df_close['Close Datetime'] == pd.NaT]

Empty DataFrame
Columns: [Close Position ID, Close Action, Close Units, Close Datetime, Close Rate, Close Spread, Close Profit USD, Close_Date, Close_unix_timestamp, EurOpen_y, EurHigh_y, EurLow_y, EurClose_y, EurWeekday_y, Close Rate_Eur, Amount_close_Eur, Spread_Eur]
Index: []

In [ ]:
# Let's build a index selector for df_close_btc
close_unit_index = 0
value_close_units = df_close_btc.loc[close_unit_index, 'Close Units']
final_close_unit_index = df_open_btc.shape[0]
fruit_list = list(range(400))
serial_number_for_loop = 0
serial_number_if_loop = 0
serial_number_elif_loop_1 = 0
serial_number_elif_loop_2 = 0
serial_number_else_loop = 0
for x in fruit_list:#while close_unit_index < final_close_unit_index:
  serial_number_for_loop = serial_number_for_loop + 1
  print('For loop run number:',serial_number_for_loop)
  i = 0
  #if value_close_units == 0:
  #  i = 1
  #else:
  #  i = 0
  print('i =',i)
  close_unit_index = close_unit_index + i
  value_close_units = df_close_btc.loc[close_unit_index, 'Close Units']
  # How to set up an upper limit on this variable?? use df.shape[0]
  # Choosing first row from df_close_btc where the units are = values_of_units
  # Assign it as new DF
  # change the reset the index and the drop the 'index' column
  df_latest_row_from_close = df_close_btc[close_unit_index:(close_unit_index+1)]
  df_latest_row_from_close.reset_index(inplace=True)
  current_close_index = df_latest_row_from_close.at[0,'index']
  df_latest_row_from_close = df_latest_row_from_close.drop('index',axis=1)
  # Get the datetime value from the df_latest_row_from_close
  close_unit_datetime = df_close_btc.loc[close_unit_index,'Close Datetime']
  print('close_unit_datetime:',close_unit_datetime)
  # find all the transaction datetimes from df_open that were opened before the close_unit_datetime
  open_datetimes_b4 = df_open_btc['Open Datetime'][df_open_btc['Open Datetime'] < close_unit_datetime]
  #Latest datetime beofore close datetime
  open_datetime_lifo = open_datetimes_b4.max()
  #if open_datetime_lifo == pd.NaT:
  #  break
  #else:
  #  continue
  print('open_datetime_lifo:',open_datetime_lifo)
  '''
  Remember that even if only one value for open_datetime_lifo is chosen
  this can still result in chosing more than one rows in that case last row 
  should be chosen
  '''
  # Corresponding row for the open_datetime_lifo 
  # let's make a new DF
  df_latest_last_row_open = df_open_btc[df_open_btc['Open Datetime'] == open_datetime_lifo]
  df_latest_last_row_open = df_latest_last_row_open[::-1]
  df_latest_last_row_open = df_latest_last_row_open[0:1]
  df_latest_last_row_open.reset_index(inplace=True)
  current_open_index = df_latest_last_row_open.at[0,'index']
  df_latest_last_row_open = df_latest_last_row_open.drop('index', axis=1)
  value_open_units = df_latest_last_row_open.loc[0,'Open Units']
  print('value_close_units:',value_close_units, 'value_open_units:',value_open_units)
  abs_diff_open_close_units = abs(value_close_units - value_open_units)
  print('abs_diff_open_close_units:',abs_diff_open_close_units)
  value_open_amount = df_latest_last_row_open.loc[0,'Open Amount_Eur']
  value_close_amount = df_latest_row_from_close.loc[0,'Amount_close_Eur']
  value_close_spread_eur = df_latest_row_from_close.loc[0,'Spread_Eur']
  close_Rate_eur = df_latest_row_from_close.loc[0,'Close Rate_Eur']
  open_Rate_eur = df_latest_last_row_open.loc[0,'Open Rate_Eur']
  #Remember that 'Open_index' and 'Close_index' columns host original indices
  # This is important as df_open_btc starts to drop rows the original indices will come in handy 
  # And in case of df_close_btc this should remain equal to the indices from DataFrame
  original_open_index = df_latest_last_row_open.at[0, 'Original_Open_index']
  #Remeber that earlier defined close_unit_index is the index of units from df_close_btc DataFrame
  # close_index should essentially be equal in integer value of close_unit_index
  close_index = df_latest_row_from_close.at[0, 'Original_Close_index']
  is_it_equal = close_unit_index == close_index
  print('(close_unit_index = close_index) is:',is_it_equal)
  if value_close_units > value_open_units:
    serial_number_if_loop = serial_number_if_loop + 1
    print('If_loop run number:',serial_number_if_loop)
    #First lets extract all the values from open DF df_latest_last_row_open
    newth_list_open_half = df_latest_last_row_open.to_dict('records')
    newth_dict_open_half = newth_list_open_half[0]
    #Then permanently delete the first row of the open DF df_latest_last_row_open from df_open_btc
    df_open_btc = df_open_btc.drop(current_open_index,axis=0)
    #Then reset index and drop the new column 'index' in df_open_btc
    df_open_btc.reset_index(inplace=True)
    df_open_btc = df_open_btc.drop('index',axis=1)
    #Now lets work on the Close_side
    #First define the changed values for df_latest_row_from_close
    changed_value_close_units = value_open_units
    changed_value_close_amount = changed_value_close_units * close_Rate_eur
    changed_value_close_spread = changed_value_close_units * value_close_spread_eur/value_close_units
    #First change the values of 'units' and 'amount' and 'spread' in the df_latest_row_from_close
    # These values will be reported
    df_latest_row_from_close.at[0,'Close Units'] = changed_value_close_units
    df_latest_row_from_close.at[0,'Amount_close_Eur'] = changed_value_close_amount
    df_latest_row_from_close.at[0,'Spread_Eur'] = changed_value_close_spread
    # Now lets extract all the values from df_latest_row_from_close
    newth_list_close_half = df_latest_row_from_close.to_dict('records')
    newth_dict_close_half = newth_list_close_half[0]
    newth_whole_dict = {**newth_dict_open_half,**newth_dict_close_half}
    # Now append the newth_whole_dict to the new records DataFrame df_lifo_btc
    df_lifo_btc = df_lifo_btc.append(newth_whole_dict, ignore_index=True)
    # and after that change the value of units and amount in original df_open_btc
    df_close_btc.at[close_unit_index,'Close Units'] = value_close_units - changed_value_close_units
    df_close_btc.at[close_unit_index,'Amount_close_Eur'] = value_close_amount - changed_value_close_amount
    df_close_btc.at[close_unit_index,'Spread_Eur'] = value_close_spread_eur - changed_value_close_spread
    print('value_close_units:',value_close_units)
    print('value_open_units:',value_open_units)
    print('close_unit_index:',close_unit_index)
    print('If_loop run number:',serial_number_if_loop,'finished')
  elif value_close_units < value_open_units:
    serial_number_elif_loop_1 = serial_number_elif_loop_1 + 1
    print('Elif_loop_1 run number:', serial_number_elif_loop_1)
    ## First lets extract all the values form close DF df_latest_row_from_close
    newth_list_close_half = df_latest_row_from_close.to_dict('records')
    newth_dict_close_half = newth_list_close_half[0]
    #First define the changed values for df_latest_row_from_close
    ## In elif statement changed values are same as we made only one change
    changed_value_close_units = value_close_units # value_open_units in if statement was here change to value_close_unit
    changed_value_close_amount = changed_value_close_units * close_Rate_eur
    changed_value_close_spread = changed_value_close_units * value_close_spread_eur/value_close_units
    # and after that change the value of units and amount and spread in original df_close_btc
    df_close_btc.at[close_unit_index,'Close Units'] = value_close_units - changed_value_close_units
    df_close_btc.at[close_unit_index,'Amount_close_Eur'] = value_close_amount - changed_value_close_amount
    df_close_btc.at[close_unit_index,'Spread_Eur'] = value_close_spread_eur - changed_value_close_spread
    #First change the values of 'units' and 'amount' and 'spread' in the df_latest_row_from_close
    # These values will be reported
    df_latest_row_from_close.at[0,'Close Units'] = changed_value_close_units
    df_latest_row_from_close.at[0,'Amount_close_Eur'] = changed_value_close_amount
    df_latest_row_from_close.at[0,'Spread_Eur'] = changed_value_close_spread
    # Now lets extract all the values from df_latest_row_from_close
    ## Now lets work on the values from open DF df_latest_last_row_lifo
    ## Remember we want to get back the values in the df_latest_row_from_close 
    ## we will have to assign changed_values for open_units and open_amount
    changed_value_open_units = value_close_units
    changed_value_open_amount = changed_value_open_units * open_Rate_eur
    df_latest_last_row_open.at[0,'Open Units'] = changed_value_close_units
    df_latest_last_row_open.at[0,'Open Amount_Eur'] = changed_value_close_amount
    ##After the values are changed extract the values which will then be reported
    newth_list_open_half = df_latest_last_row_open.to_dict('records')
    newth_dict_open_half = newth_list_open_half[0]
    ## and then this time change the original values in the df_open_units
    newth_whole_dict = {**newth_dict_open_half,**newth_dict_close_half}
    # Now append the newth_whole_dict to the new records DataFrame df_lifo_btc
    df_lifo_btc = df_lifo_btc.append(newth_whole_dict, ignore_index=True)
    # and after that change the value of units and amount in original df_open_btc
    df_open_btc.at[current_open_index,'Open Units'] = value_open_units - changed_value_open_units
    df_open_btc.at[current_open_index,'Open Amount_Eur'] = value_open_amount - changed_value_open_amount
    print('value_close_units:',value_close_units)
    print('value_open_units:',value_open_units)
    print('close_unit_index:',close_unit_index)
    print('Elif_loop_1 run number:', serial_number_elif_loop_1, 'finished')
  elif value_close_units == value_open_units:
    serial_number_elif_loop_2 = serial_number_elif_loop_2 + 1
    if value_close_units == 0:
      print('We are running value_close_units == 0 condition')
      print('This is in the Elif_loop_number_2:',serial_number_elif_loop_2)
      #Then permanently delete the first row of the open DF df_latest_last_row_open from df_open_btc
      df_open_btc = df_open_btc.drop(current_open_index,axis=0)
      #Then reset index and drop the new column 'index' in df_open_btc
      df_open_btc.reset_index(inplace=True)
      df_open_btc = df_open_btc.drop('index',axis=1)
      print('We are breaking')
      break
    else:
      #First lets extract all the values from open DF df_latest_last_row_open
      newth_list_open_half = df_latest_last_row_open.to_dict('records')
      newth_dict_open_half = newth_list_open_half[0]
      #Then permanently delete the first row of the open DF df_latest_last_row_open from df_open_btc
      df_open_btc = df_open_btc.drop(current_open_index,axis=0)
      #Then reset index and drop the new column 'index' in df_open_btc
      df_open_btc.reset_index(inplace=True)
      df_open_btc = df_open_btc.drop('index',axis=1)
      ### Second lets extract all the values form close DF df_latest_row_from_close
      newth_list_close_half = df_latest_row_from_close.to_dict('records')
      newth_dict_close_half = newth_list_close_half[0]
      #First define the changed values for df_latest_row_from_close
      changed_value_close_units = value_open_units
      changed_value_close_amount = changed_value_close_units * close_Rate_eur
      changed_value_close_spread = changed_value_close_units * value_close_spread_eur/value_close_units
      # and after that change the value of units and amount in original df_open_btc
      df_close_btc.at[close_unit_index,'Close Units'] = value_close_units - changed_value_close_units
      df_close_btc.at[close_unit_index,'Amount_close_Eur'] = value_close_amount - changed_value_close_amount
      df_close_btc.at[close_unit_index,'Spread_Eur'] = value_close_spread_eur - changed_value_close_spread
    print('value_close_units:',value_close_units)
    print('value_open_units:',value_open_units)
    print('close_unit_index:',close_unit_index)
    print('Elif_loop_2 run number:', serial_number_elif_loop_2, 'finished')
  else:
    serial_number_else_loop = serial_number_else_loop + 1
    print('Do we need to write more code? The answer is a: BIG YES!!')
    print('Or on second thought this is a silly mistake!!!')
    print('value_close_units:',value_close_units)
    print('value_open_units:',value_open_units)
    print('close_unit_index:',close_unit_index)
    print('serial_number_else_loop:', serial_number_else_loop, 'finished')
    print('We are breaking here!!')
    break
  value_close_units = df_close_btc.loc[close_unit_index, 'Close Units']
  if value_close_units == 0:
    i = 1
  else:
    i = 0
  print('i =',i)
  close_unit_index = close_unit_index + i
  print('For loop run number:',serial_number_for_loop,'finished')
  print('****************************************')

For loop run number: 1
i = 0
close_unit_datetime: 2021-08-17 07:03:51
open_datetime_lifo: 2021-05-22 05:55:05
value_close_units: 35.620274 value_open_units: 1.240522
abs_diff_open_close_units: 34.379752
(close_unit_index = close_index) is: True
If_loop run number: 1
value_close_units: 35.620274
value_open_units: 1.240522
close_unit_index: 0
If_loop run number: 1 finished
i = 0
For loop run number: 1 finished
****************************************
For loop run number: 2
i = 0
close_unit_datetime: 2021-08-17 07:03:51
open_datetime_lifo: 2021-05-21 14:18:59
value_close_units: 34.379752 value_open_units: 4.072822
abs_diff_open_close_units: 30.30693
(close_unit_index = close_index) is: True
If_loop run number: 2
value_close_units: 34.379752
value_open_units: 4.072822
close_unit_index: 0
If_loop run number: 2 finished
i = 0
For loop run number: 2 finished
****************************************
For loop run number: 3
i = 0
close_unit_datetime: 2021-08-17 07:03:51
open_datetime_lifo: 2021-05-19 11:26:38
value_close_units: 30.30693 value_open_units: 35.620274
abs_diff_open_close_units: 5.313344000000001
(close_unit_index = close_index) is: True
Elif_loop_1 run number: 1
value_close_units: 30.30693
value_open_units: 35.620274
close_unit_index: 0
Elif_loop_1 run number: 1 finished
i = 1
For loop run number: 3 finished
****************************************
For loop run number: 4
i = 0
close_unit_datetime: 2021-09-27 08:26:17
open_datetime_lifo: 2021-09-24 06:31:12
value_close_units: 37.229972 value_open_units: 54.660666
abs_diff_open_close_units: 17.430694000000003
(close_unit_index = close_index) is: True
Elif_loop_1 run number: 2
value_close_units: 37.229972
value_open_units: 54.660666
close_unit_index: 1
Elif_loop_1 run number: 2 finished
i = 1
For loop run number: 4 finished
****************************************
For loop run number: 5
i = 0
close_unit_datetime: 2021-09-27 08:26:21
open_datetime_lifo: 2021-09-24 06:31:12
value_close_units: 4.072822 value_open_units: 17.430694000000003
abs_diff_open_close_units: 13.357872000000002
(close_unit_index = close_index) is: True
Elif_loop_1 run number: 3
value_close_units: 4.072822
value_open_units: 17.430694000000003
close_unit_index: 2
Elif_loop_1 run number: 3 finished
i = 1
For loop run number: 5 finished
****************************************
For loop run number: 6
i = 0
close_unit_datetime: 2021-09-28 15:23:32
open_datetime_lifo: 2021-09-24 06:31:12
value_close_units: 45.619865 value_open_units: 13.357872000000002
abs_diff_open_close_units: 32.261993
(close_unit_index = close_index) is: True
If_loop run number: 3
value_close_units: 45.619865
value_open_units: 13.357872000000002
close_unit_index: 3
If_loop run number: 3 finished
i = 0
For loop run number: 6 finished
****************************************
For loop run number: 7
i = 0
close_unit_datetime: 2021-09-28 15:23:32
open_datetime_lifo: 2021-09-10 13:34:11
value_close_units: 32.261993 value_open_units: 45.619865
abs_diff_open_close_units: 13.357872
(close_unit_index = close_index) is: True
Elif_loop_1 run number: 4
value_close_units: 32.261993
value_open_units: 45.619865
close_unit_index: 3
Elif_loop_1 run number: 4 finished
i = 1
For loop run number: 7 finished
****************************************
For loop run number: 8
i = 0
close_unit_datetime: 2021-09-28 15:27:07
open_datetime_lifo: 2021-09-10 13:34:11
value_close_units: 54.660666 value_open_units: 13.357872
abs_diff_open_close_units: 41.302794
(close_unit_index = close_index) is: True
If_loop run number: 4
value_close_units: 54.660666
value_open_units: 13.357872
close_unit_index: 4
If_loop run number: 4 finished
i = 0
For loop run number: 8 finished
****************************************
For loop run number: 9
i = 0
close_unit_datetime: 2021-09-28 15:27:07
open_datetime_lifo: 2021-08-25 04:40:50
value_close_units: 41.302794 value_open_units: 37.229972
abs_diff_open_close_units: 4.072822000000002
(close_unit_index = close_index) is: True
If_loop run number: 5
value_close_units: 41.302794
value_open_units: 37.229972
close_unit_index: 4
If_loop run number: 5 finished
i = 0
For loop run number: 9 finished
****************************************
For loop run number: 10
i = 0
close_unit_datetime: 2021-09-28 15:27:07
open_datetime_lifo: 2021-05-19 11:26:38
value_close_units: 4.072822000000002 value_open_units: 5.313344000000001
abs_diff_open_close_units: 1.2405219999999986
(close_unit_index = close_index) is: True
Elif_loop_1 run number: 5
value_close_units: 4.072822000000002
value_open_units: 5.313344000000001
close_unit_index: 4
Elif_loop_1 run number: 5 finished
i = 1
For loop run number: 10 finished
****************************************
For loop run number: 11
i = 0
close_unit_datetime: 2021-11-17 14:34:02
open_datetime_lifo: 2021-10-07 23:00:26
value_close_units: 47.264043 value_open_units: 47.264043
abs_diff_open_close_units: 0.0
(close_unit_index = close_index) is: True
value_close_units: 47.264043
value_open_units: 47.264043
close_unit_index: 5
Elif_loop_2 run number: 1 finished
i = 1
For loop run number: 11 finished
****************************************
For loop run number: 12
i = 0
close_unit_datetime: 2021-11-17 14:34:06
open_datetime_lifo: 2021-10-06 12:47:23
value_close_units: 20.037794 value_open_units: 20.037794
abs_diff_open_close_units: 0.0
(close_unit_index = close_index) is: True
value_close_units: 20.037794
value_open_units: 20.037794
close_unit_index: 6
Elif_loop_2 run number: 2 finished
i = 1
For loop run number: 12 finished
****************************************
For loop run number: 13
i = 0
close_unit_datetime: 2021-11-17 14:34:09
open_datetime_lifo: 2021-05-19 11:26:38
value_close_units: 1.240522 value_open_units: 1.2405219999999986
abs_diff_open_close_units: 1.3322676295501878e-15
(close_unit_index = close_index) is: True
If_loop run number: 6
value_close_units: 1.240522
value_open_units: 1.2405219999999986
close_unit_index: 7
If_loop run number: 6 finished
i = 0
For loop run number: 13 finished
****************************************
For loop run number: 14
i = 0
close_unit_datetime: 2021-11-17 14:34:09
open_datetime_lifo: NaT

KeyError: ignored

In [ ]:
df_lifo_btc

In [ ]:
df_open_btc

Empty DataFrame
Columns: [Original_Open_index, Open Position ID, Open Action, Open Amount, Open Units, Open Datetime, Open Rate, Open_Date, Open_unix_timestamp, EurOpen_x, EurHigh_x, EurLow_x, EurClose_x, EurWeekday_x, Open Amount_Eur, Open Rate_Eur]
Index: []

In [ ]:
df_close_btc

,Original_Close_index,Close Position ID,Close Action,Close Units,Close Datetime,Close Rate,Close Spread,Close Profit USD,Close_Date,Close_unix_timestamp,EurOpen_y,EurHigh_y,EurLow_y,EurClose_y,EurWeekday_y,Close Rate_Eur,Amount_close_Eur,Spread_Eur
0,0,1165828074,Buy Uniswap,0.000000e+00,2021-08-17 07:03:51,28.43,40.29,12.84,17/08/2021 00:00,1629183831,1.177995,1.178411,1.171056,1.177995,Tuesday,24.125708,1.347368e-07,0.000000e+00
1,1,1287078778,Buy Uniswap,0.000000e+00,2021-09-27 08:26:17,24.30,35.98,-107.27,27/09/2021 00:00,1632731177,1.172209,1.172800,1.168661,1.172305,Monday,20.719645,1.033683e-07,-3.552714e-15
2,2,1171090484,Buy Uniswap,0.000000e+00,2021-09-27 08:26:21,24.31,3.94,-0.99,27/09/2021 00:00,1632731181,1.172209,1.172800,1.168661,1.172305,Monday,20.728172,-1.410180e-08,0.000000e+00
3,3,1306979118,Buy Uniswap,0.000000e+00,2021-09-28 15:23:32,23.59,42.81,19.07,28/09/2021 00:00,1632842612,1.169604,1.170600,1.166997,1.169680,Tuesday,20.152059,1.405341e-07,0.000000e+00
4,4,1321772630,Buy Uniswap,0.000000e+00,2021-09-28 15:27:07,23.49,51.08,114.43,28/09/2021 00:00,1632842827,1.169604,1.170600,1.166997,1.169680,Tuesday,20.066633,1.727550e-07,0.000000e+00
5,5,1342765768,Buy Uniswap,0.000000e+00,2021-11-17 14:34:02,21.13,39.72,-236.32,17/11/2021 00:00,1637159642,1.131618,1.133400,1.127053,1.132118,Wednesday,18.643021,-9.390305e-08,0.000000e+00
6,6,1340329554,Buy Uniswap,0.000000e+00,2021-11-17 14:34:06,21.13,16.84,-77.11,17/11/2021 00:00,1637159646,1.131618,1.133400,1.127053,1.132118,Wednesday,18.643021,-3.567408e-08,-1.776357e-15
7,7,1172066980,Buy Uniswap,1.332268e-15,2021-11-17 14:34:09,21.12,1.04,1.20,17/11/2021 00:00,1637159649,1.131618,1.133400,1.127053,1.132118,Wednesday,18.634198,1.049248e-09,9.992007e-16

In [ ]:
df_lifo_btc.dtypes

In [ ]:
df_lifo_btc['time_difference'] = df_lifo_btc['Close Datetime'] - df_lifo_btc['Open Datetime']
df_lifo_btc['time_difference_days'] = df_lifo_btc['time_difference'] / np.timedelta64(1, 'D')
df_lifo_btc_taxable = df_lifo_btc[df_lifo_btc['time_difference_days'] < 365]
df_lifo_btc_taxable_2020 = df_lifo_btc_taxable[df_lifo_btc_taxable['Close_unix_timestamp'] <= 1609455599]
df_lifo_btc_taxable_2020_2021 = df_lifo_btc_taxable[df_lifo_btc_taxable['Close_unix_timestamp'] <= 1640991599]
df_lifo_btc_taxable_2021 = df_lifo_btc_taxable_2020_2021[df_lifo_btc_taxable_2020_2021['Close_unix_timestamp'] > 1609455599]
df_lifo_btc_taxable_2022 = df_lifo_btc_taxable[df_lifo_btc_taxable['Close_unix_timestamp'] > 1640991599]
print('Sum of all open positions for the year 2020 in eur:',df_lifo_btc_taxable_2020['Open Amount_Eur'].sum())
print('Sum of all closed positions for the year 2020 in eur:',df_lifo_btc_taxable_2020['Amount_close_Eur'].sum())
print('Sum of all open positions for the year 2021 in eur:',df_lifo_btc_taxable_2021['Open Amount_Eur'].sum())
print('Sum of all closed positions for the year 2021 in eur:',df_lifo_btc_taxable_2021['Amount_close_Eur'].sum())
print('Sum of all open positions for the year 2022 in eur:',df_lifo_btc_taxable_2022['Open Amount_Eur'].sum())
print('Sum of all closed positions for the year 2022 in eur:',df_lifo_btc_taxable_2022['Amount_close_Eur'].sum())

Sum of all open positions for the year 2020 in eur: 0.0
Sum of all closed positions for the year 2020 in eur: 0.0
Sum of all open positions for the year 2021 in eur: 3819.2950236049173
Sum of all closed positions for the year 2021 in eur: 3754.484137678951
Sum of all open positions for the year 2022 in eur: 0.0
Sum of all closed positions for the year 2022 in eur: 0.0