<a href="https://colab.research.google.com/github/VijayTaori/Lifo_step1/blob/main/Detailed_Lifo_step10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import datetime as dt
import time
import calendar
df_open = pd.read_csv('/content/et_open_alldata.csv')
df_close = pd.read_csv('/content/et_close_alldata.csv')
#df_open['open_unix_timestamp'] = pd.to_numeric(df_open['open_unix_timestamp'])
df_close['Close Datetime'] = pd.to_datetime(df_close['Close_unix_timestamp'],dayfirst=True,unit='s')
df_open['Open Datetime'] = pd.to_datetime(df_open['Open_unix_timestamp'],dayfirst=True,unit='s')
df_close_btc = df_close[df_close['Close Action'] =='Buy Bitcoin']
df_open_btc = df_open[df_open['Open Action'] =='Buy Bitcoin']
df_close_btc.reset_index(inplace=True)
df_close_btc.drop('index', axis=1, inplace=True)
df_close_btc.reset_index(inplace=True)
df_close_btc.rename(columns={'index':'Close_index'},inplace=True)
df_open_btc.reset_index(inplace=True)
df_open_btc.drop('index', axis=1, inplace=True)
df_open_btc.reset_index(inplace=True)
df_open_btc.rename(columns={'index':'Open_index'},inplace=True)
data_btc = {}
df_lifo_btc = pd.DataFrame(data_btc, 
                           columns=['Open_index','Close_index',
                                    'Open Position ID', 'Close Position ID',
                                    'Open Units','Close Units','Spread_Eur',
                                    'Open Amount_Eur','Amount_close_Eur',
                                    'Open Datetime', 'Close Datetime',
                                    'Open Rate_Eur', 'Close Rate_Eur',
                                    'Open Action', 'Close Action', 
                                    'Open Amount','Close Rate', 'Open Rate',
                                    'Close Spread', 'Close Profit USD',
                                    'Close_Date','Open_Date',
                                    'Close_unix_timestamp','EurOpen_y', 
                                    'EurHigh_y','EurLow_y', 'EurClose_y',
                                    'EurWeekday_y', 'Open_unix_timestamp',
                                    'EurOpen_x', 'EurHigh_x','EurLow_x', 
                                    'EurClose_x','EurWeekday_x'
                                    ]
                           )
# Let's build a index selector for df_close_btc
close_unit_index = 0
final_close_unit_index = df_open_btc.shape[0]
fruit_list = list(range(200))
serial_number_for_loop = 0
serial_number_if_loop = 0
serial_number_elif_loop_1 = 0
serial_number_elif_loop_2 = 0
serial_number_else_loop = 0

/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [3]:
df_open_btc

,Open_index,Open Position ID,Open Action,Open Amount,Open Units,Open Datetime,Open Rate,Open_Date,Open_unix_timestamp,EurOpen_x,EurHigh_x,EurLow_x,EurClose_x,EurWeekday_x,Open Amount_Eur,Open Rate_Eur
0,0,599295474,Buy Bitcoin,100.00,0.014029,2020-04-17 13:09:20,7128.14,17/04/2020 00:00,1587128960,1.086012,1.089325,1.081268,1.085847,Friday,92.484010,6592.389676
1,1,599996081,Buy Bitcoin,100.00,0.014149,2020-04-17 18:42:42,7067.56,17/04/2020 00:00,1587148962,1.086012,1.089325,1.081268,1.085847,Friday,92.484010,6536.362863
2,2,600052383,Buy Bitcoin,750.00,0.103664,2020-04-18 13:49:32,7234.89,18/04/2020 00:00,1587217772,1.086012,1.089325,1.081268,1.085847,Saturday,693.630071,6691.116356
3,3,600057583,Buy Bitcoin,150.00,0.020751,2020-04-18 16:48:30,7228.58,18/04/2020 00:00,1587228510,1.086012,1.089325,1.081268,1.085847,Saturday,138.726014,6685.280615
4,4,600061986,Buy Bitcoin,31.81,0.004376,2020-04-18 21:07:10,7269.44,18/04/2020 00:00,1587244030,1.086012,1.089325,1.081268,1.085847,Saturday,29.419163,6723.069581
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,199,1353186945,Buy Bitcoin,100.00,0.001611,2021-10-18 21:47:56,62087.07,18/10/2021 00:00,1634593676,1.159595,1.161211,1.157300,1.159703,Monday,86.408019,53648.207030
200,200,1354684971,Buy Bitcoin,438.64,0.006812,2021-10-19 20:54:00,64396.26,19/10/2021 00:00,1634676840,1.161454,1.167000,1.161454,1.161386,Tuesday,377.664548,55444.520400
201,201,1361963252,Buy Bitcoin,94.37,0.001490,2021-10-25 19:00:27,63355.46,25/10/2021 00:00,1635188427,1.164131,1.166861,1.159326,1.164009,Monday,81.400745,54648.528540
202,202,1368128599,Buy Bitcoin,782.56,0.012804,2021-10-29 09:51:32,61119.72,29/10/2021 00:00,1635501092,1.168374,1.169180,1.154668,1.168361,Friday,677.735938,52932.721790
203,203,1370705010,Buy Bitcoin,397.37,0.006407,2021-11-01 11:59:53,62022.88,01/11/2021 00:00,1635767993,1.155936,1.159326,1.154668,1.155668,Monday,344.142212,53714.903330